-- AlterTable
ALTER TABLE `families` ADD COLUMN `union_status` ENUM('ONGOING', 'ENDED_BY_DEATH', 'DIVORCED', 'SEPARATED', 'ANNULLED') NOT NULL DEFAULT 'ONGOING',
    MODIFY `union_type` ENUM('MARRIAGE', 'PARTNERSHIP', 'EXTRAMARITAL', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN';
