export const SEX_VALUES = ["MALE", "FEMALE", "UNKNOWN"] as const;
export const DATE_PRECISION_VALUES = ["EXACT", "ABOUT", "BEFORE", "AFTER", "UNKNOWN"] as const;
export const UNION_TYPE_VALUES = ["MARRIAGE", "PARTNERSHIP", "EXTRAMARITAL", "UNKNOWN"] as const;
export const UNION_STATUS_VALUES = ["ONGOING", "ENDED_BY_DEATH", "DIVORCED", "SEPARATED", "ANNULLED"] as const;
export const CHILD_RELATION_TYPE_VALUES = ["BIOLOGICAL", "ADOPTED", "FOSTER", "STEP", "UNKNOWN"] as const;
